readme修正
matsuo-y/git-practice pull request #9
Opened 2016-10-26 06:13 UTC by matsuo-y

下記を修正しました。

- [ ] staging→stagingブランチに修正
- [ ] 昼食のブランチ作成者を削除、PR作成者の作業内容を修正
- [ ] 昼食でstagingブランチへマージする際のレビューについて追記

2016-10-26 06:15 UTC, matsuo-y commented
@opst-fujimoto 
README.mdの記述を一部修正したので、レビューをお願いします。

2016-10-26 06:24 UTC, opst-fujimoto commented
お客さんの検収を想定して、「検収担当者」をつくりましょう。
最終的に、stagingブランチへのマージボタンを押す役割を持つ人

2016-10-26 06:24 UTC, ghost requested changes
コメントしたよ

2016-10-26 06:24 UTC, opst-fujimoto commented on README.md
> +- PR担当者(昼食報告、1名)：stagingブランチからissue用ブランチを作成して作業を行い、stagingブランチへのPRを作成する
branch作成者は残しましょ。リポジトリ間の差異を、認識しやすくするために

2016-10-26 06:24 UTC, opst-fujimoto commented on README.md
> +- issue作成者：朝食リポジトリでのissue作成、issue用ブランチへのPRレビュー(最低1回は修正依頼を出す)、staging・masterブランチへのPR作成を行う
複数行にわけましょうか、こんな感じで

- issue作成者：
 - 朝食リポジトリでのissue作成
 - issue用ブランチへのPRレビュー(最低1回は修正依頼を出す)
 - staging・masterブランチへのPR作成を行う

2016-10-26 09:00 UTC, matsuo-y commented
@opst-fujimoto 指摘事項の修正、およびブランチの前提条件を追記しました。
お手数をおかけしますが、再度レビューをお願いいたします。

2016-10-27 05:08 UTC, ghost requested changes

2016-10-27 05:13 UTC, matsuo-y commented
@opst-fujimoto 
指摘事項を修正しました。
再度ご確認をお願いいたします。

2016-10-28 01:08 UTC, opst-fujimoto commented on README.md
> + - stagingブランチへのリリース(PRレビュー)実施
stagingブランチへのリリース　は表現がおかしいですね

開発担当者が、issueブランチをもとにstagingブランチへのPRを作成し、issueブランチをデプロイした結果を確認した後、
検収担当者が、stagingブランチへのPRをレビューし、マージする

2016-10-28 01:08 UTC, opst-fujimoto commented on README.md
> + - masterブランチへのリリース(PRレビュー)実施
masterブランチへのリリース　も表現がおかしいですね

stagingブランチをもとにmasterブランチへのPRを作成し、stagingブランチをデプロイした結果を確認した後、masterブランチへのPRをマージする

2016-10-28 01:21 UTC, matsuo-y commented on README.md
> + - stagingブランチへのリリース(PRレビュー)実施
こちらの修正についてですが、朝食リポジトリ(複数の開発担当者が関わるパターン)では複数人の開発担当者の作業が全て終わってからstagingブランチへのPR作成になると思うのですが、
開発担当者のうちの誰か1人が全ての開発が終わっていることを確認してPRを作成する流れになりますでしょうか？

2016-10-28 01:45 UTC, opst-fujimoto commented on README.md
> + - masterブランチへのリリース(PRレビュー)実施
issue発行者とリリース担当者が同じになる認識であっていますが、あえて、役割を明確にするために、呼び名を変えました。
また、各担当者の役割は、時系列とともに、下に読んでいくと、認識しやすくなるかと

2016-10-28 01:53 UTC, matsuo-y commented
@opst-fujimoto 
再度修正してみましたので、ご確認をお願いいたします。

2016-10-28 01:57 UTC, opst-fujimoto commented
ブランチについて

の章は、リポジトリの章の前に、書きましょう。前提条件として、先に読めたほうがよい

2016-10-28 01:58 UTC, opst-fujimoto commented on README.md
> +issue用ブランチはstagingブランチから切る
この1文は、もう別途記載されているので、不要かな

2016-10-28 06:07 UTC, matsuo-y commented
@opst-fujimoto 

>ブランチについて
>の章は、リポジトリの章の前に、書きましょう。前提条件として、先に読めたほうがよい

説明を前半に移動しました。
再度ご確認をお願いいたします。

2016-10-28 08:20 UTC, ghost requested changes

2016-10-28 08:20 UTC, opst-fujimoto commented on README.md
> +issueブランチはstagingブランチから切る
ここはいらない。ブランチの種類に定義を書いているので。

2016-10-28 08:23 UTC, ghost requested changes

2016-10-28 08:23 UTC, opst-fujimoto commented on README.md
>  - review app環境(PRごとに作成)：https://git-practice-lunch-pr-{N}.herokuapp.com/
対象ブランチ　を書くように修正してください

2016-10-28 08:44 UTC, matsuo-y commented
@opst-fujimoto 
レビュー指摘箇所を修正しました。
再度レビューをお願いします。

2016-10-28 08:53 UTC, ghost approved these changes

2016-10-28 08:53 UTC, merged